export const Events2025 = {
  MARCH: [
    {
      title: "Trinca & GDG",
      days: "19",
      country: "Brazil",
      state: "Porto Alegre",
      imageUrl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRrYx5m2oonTn4honjTx1J9qkgP3wwd1nuzNinm8ykoWNO2oblKc123oBHeYjKvRL58ds&usqp=CAU",
      format: "In Person",
      eventUrl:
        "https://gdg.community.dev/events/details/google-gdg-porto-alegre-presents-trinca-amp-gdg/",
      tags: ["ia", "leadership"],
    },
    {
      title: "React Paris",
      days: "20-21",
      country: "Paris",
      imageUrl:
        "https://react.paris/_next/image?url=https%3A%2F%2Fassets.reactbricks.com%2FWRBsx9AS2_St2yj%2Fimages%2Foriginal%2Fj1RV21AqwTYo_7K.webp&w=3840&q=75",
      format: "Paris, France & Online",
      eventUrl: "https://react.paris/",
      tags: ["react", "frontend", "javascript"],
    },
    {
      title: "PGDay Paris",
      days: "20",
      country: "Paris",
      imageUrl:
        "https://2025.pgday.paris/static/fdc7362/img/main_logo_2025.png",
      format: "In Person",
      eventUrl: "https://2025.pgday.paris/",
      tags: ["data"],
    },
    {
      title: "SecOps Summit 2025",
      days: "20",
      country: "Brazil",
      state: "São Paulo",
      imageUrl:
        "https://www.secopssummit.com.br/uploads/p9499c73364402a4eea523c2cd74e6c34.jpg",
      format: "In Person",
      eventUrl: "https://www.secopssummit.com.br/",
      tags: ["security", "IA"],
    },
    {
      title: "GitTogether São Paulo",
      days: "20",
      country: "Brazil",
      state: "São Paulo",
      imageUrl:
        "https://secure.meetupstatic.com/photos/event/8/e/5/f/600_526116447.webp?w=384",
      format: "In Person",
      eventUrl: "https://www.meetup.com/gittogether-brasil/events/306033353/",
      tags: ["Open Source", "web"],
    },
    {
      title: "Data World Xperience 2025",
      days: "20-21",
      country: "Brazil",
      state: "Florianópolis",
      imageUrl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTopJG_KCCvf6-8T6YTgvwIYIDXGcmOy-Fjog&s",
      format: "In Person",
      eventUrl: "https://www.meetup.com/gittogether-brasil/events/306033353/",
      tags: ["data", "IA"],
    },
    {
      title: "Frontrunners",
      days: "21",
      country: "USA",
      imageUrl: "https://frontrunners.tech/images/banner/DCJS.png",
      format: "In Person",
      eventUrl: "https://frontrunners.tech/",
      tags: ["javascript"],
    },
    {
      title: "BSidesRJ - 2025",
      days: "22",
      country: "Brazil",
      state: "Rio de Janeiro",
      imageUrl:
        "https://media.licdn.com/dms/image/v2/D4D0BAQGix4UhKLRCgA/company-logo_200_200/company-logo_200_200/0/1719256636588/bsidesrj_logo?e=2147483647&v=beta&t=MJdAOS1j3XlEAh9rkpRpP_tr_BCVL5fLUPiRX8-bs-s",
      format: "In Person",
      eventUrl: "https://bsidesrj.com.br/",
      tags: ["security"],
    },
    {
      title: "International Women's Day Curitiba 2025",
      days: "22",
      country: "Brazil",
      state: "Paraná",
      imageUrl:
        "https://secure.meetupstatic.com/photos/event/2/d/9/9/600_525851673.webp?w=384",
      format: "In Person",
      eventUrl:
        "https://www.meetup.com/pt-br/women-techmakers-curitiba/events/305753276/",
      tags: ["networking"],
    },
    {
      title: "KCD Rio de Janeiro 2025",
      days: "22",
      country: "Brazil",
      state: "Rio de Janeiro",
      imageUrl:
        "https://res.cloudinary.com/startup-grind/image/fetch/c_scale,w_2560/c_crop,h_650,w_2560,y_0.0_mul_h_sub_0.0_mul_650/c_crop,h_650,w_2560/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/https://res.cloudinary.com/startup-grind/image/upload/c_fill%2Cdpr_2.0%2Cf_auto%2Cg_center%2Cq_auto:good/v1/gcs/platform-data-cncf/chapter_banners/WhatsApp%2520Image%25202025-03-13%2520at%252013.42.03_2edXyhL.jpeg",
      format: "In Person",
      eventUrl: "https://community.cncf.io/kcd-brasil/",
      tags: ["general"],
    },
    {
      title: "Software Architecture Summit",
      days: "24-26",
      country: "France",
      imageUrl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT251DOiXipzyw48osbz4BTS3ukRkBk3xSxnA&s",
      format: "In Person",
      eventUrl: "https://software-architecture-summit.de/muenchen/",
      tags: ["security", "iot"],
    },
    {
      title: "FIAP Masterclass - Next Level Innovation",
      days: "25",
      country: "Brazil",
      state: "São Paulo",
      imageUrl:
        "https://secure.meetupstatic.com/photos/event/3/d/6/c/600_526755724.webp?w=384",
      format: "In Person",
      eventUrl: "https://www.meetup.com/fiapmeetups/events/306461292/",
      tags: ["innovation", "IA", "Business Strategy"],
    },
    {
      title: "Agile India 2025",
      days: "25-27",
      country: "India",
      state: "Bengaluru",
      imageUrl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSK-09vEV6QnbB8oDuN5tGjLURHdhW1s7eDfw&s",
      format: "In Person",
      eventUrl: "https://2025.agileindia.org/",
      tags: ["general"],
    },
    {
      title: "Security Girls 2025",
      days: "26",
      country: "Brazil",
      state: "São Paulo",
      imageUrl:
        "https://secure.meetupstatic.com/photos/event/3/7/2/c/600_526334124.webp?w=384",
      format: "In Person",
      eventUrl:
        "https://www.meetup.com/microsoft-reactor-sao-paulo/events/306239922/",
    },
    {
      title: "TDC Summit São Paulo",
      days: "26-27",
      country: "Brazil",
      imageUrl: "https://thedevconf.com/assets/img/summit/TopoTDC3.webp",
      format: "In Person",
      eventUrl: "https://thedevconf.com/tdc/2025/summit-sao-paulo/",
      tags: ["IA"],
    },
    {
      title: "The Future of Software",
      days: "26",
      country: "UK",
      state: "London",
      imageUrl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_SReeEkWkXg93E8VItgmTTyVgtVuG63IU1Q&s",
      format: "In Person",
      eventUrl: "https://www.thefutureofsoftware.com/london",
      tags: ["general"],
    },
    {
      title: "WebDev & AI Day",
      days: "27",
      imageUrl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQacamCP_vuZ9Bg4U_1tFmgM8nxnrSVbOB-iQ&s",
      format: "Online",
      eventUrl: "https://www.wearedevelopers.com/events/webdev-ai-day",
      tags: ["data"],
    },
    {
      title: "SymfonyLive Paris 2025",
      days: "27-28",
      country: "France",
      state: "Paris",
      imageUrl:
        "https://symfony.com/uploads/assets/blog/sfliveparis2025-blog-at-2x.png",
      format: "In Person",
      eventUrl: "https://live.symfony.com/2025-paris/",
      tags: ["php"],
    },
    {
      title: "Productivity Conf | Devs & Tech Leaders",
      days: "27-28",
      imageUrl: "https://media.graphassets.com/cI2CzJdQDest8A98WSOM",
      format: "Online",
      eventUrl: "https://productivityconf.com/developers/",
      tags: ["data", "product", "testing"],
    },
    {
      title: "Sem Servidor Conf 2025",
      days: "28",
      country: "Brazil",
      state: "Florianópolis",
      imageUrl: "https://images.sympla.com.br/6785c2f7a6128-xs.png",
      format: "In Person",
      eventUrl: "https://semservidor.com.br/sem-servidor-conf/",
      tags: ["general"],
    },
    {
      title: "1º Encontro de Mulheres em Tecnologia no Cerrado",
      days: "29",
      country: "Brazil",
      state: "Brasilia",
      imageUrl:
        "https://secure.meetupstatic.com/photos/event/8/1/c/5/600_526353221.webp?w=384",
      format: "In Person",
      eventUrl:
        "https://www.meetup.com/aws-user-group-brasilia/events/306265242/?slug=aws-user-group-brasilia&eventId=305233284&isFirstPublish=true",
      tags: ["career", "cloud", "general"],
    },
    {
      title: "RUST Asia",
      days: "28",
      country: "China",
      state: "Hong Kong",
      imageUrl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLKBeS8g18FR2O_8KcqkZDP3ZcgTmj7OU2mQ&s",
      format: "In Person",
      eventUrl: "https://www.rustasiaconf.com/",
      tags: ["rust"],
    },
  ],
  APRIL: [
    {
      title: "KubeCon + CloudNativeCon Europe",
      days: "01-04",
      country: "UK",
      state: "London",
      imageUrl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTU4GvJUwpwZj2EnyeiDWx2p0_Qm-ubzAIb6Q&s",
      format: "In Person & Online",
      eventUrl:
        "https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/",
      tags: ["devops"],
    },
    {
      title: "Computer on the beach",
      days: "02-05",
      country: "Brazil",
      state: "Santa Catarina",
      imageUrl:
        "https://informatica.ifgoiano.edu.br/images/icagenda/files/COTB.png",
      format: "In Person",
      eventUrl: "https://computeronthebeach.com.br/",
      tags: ["general"],
    },
    {
      title: "Agile Trends 2025",
      days: "08-11",
      country: "Brazil",
      state: "São Paulo",
      imageUrl:
        "https://agiletrendsbr.com/2021/wp-content/uploads/2014/01/logo-agiletrends.png",
      format: "In Person",
      eventUrl: "https://agiletrendsbr.com/",
      tags: ["IA", "agile"],
    },
    {
      title: "Hacking na Web Day - Recife",
      days: "12",
      country: "Brazil",
      state: "Recife",
      imageUrl: "https://images.sympla.com.br/6781d40d13914-xs.png",
      format: "In Person",
      eventUrl:
        "https://www.sympla.com.br/evento/hnwd-recife-2025/2820464?referrer=linktr.ee",
      tags: ["web", "general"],
    },
    {
      title: "React Miami",
      days: "17-18",
      country: "USA",
      state: "Miami",
      imageUrl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfAE-NCb1gdd_hDwXTZ_PwPe_Dl6FTwhdkeA&s",
      format: "In Person",
      eventUrl: "https://www.reactmiami.com/",
      tags: ["javascript", "frontend"],
    },
    {
      title: "Node Congress",
      days: "17-18",
      imageUrl: "https://nodecongress.com/img/ogImage.png",
      format: "Online",
      eventUrl: "https://nodecongress.com/",
      tags: ["javascript"],
    },
    {
      title: "CityJS London",
      days: "23-25",
      country: "UK",
      state: "London",
      imageUrl: "https://cityjsconf.org/images/site/2019.jpg",
      format: "In Person & Online",
      eventUrl: "https://london.cityjsconf.org/",
      tags: ["javascript"],
    },
    {
      title: "Web Summit Rio 2025",
      days: "27-30",
      country: "Brazil",
      state: "Rio de Janeiro",
      imageUrl:
        "https://adesampa.com.br/adeeditais/wp-content/uploads/2022/09/web-1024x576.jpeg",
      format: "In Person",
      eventUrl: "https://rio.websummit.com/",
      tags: ["business", "general"],
    },
  ],
};
